version: '3.8'

services:
    db:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=@GwayanKwaks97
            - POSTGRES_DB=mindfulblog
        container_name: mindfulblogwebapp_db
  
    mindfulblog:
      build:
        context: .
        dockerfile: Dockerfile
      restart: always
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - ./mindfulblog:/mindfulblog
      ports:
        - 8000:8000
      env_file:
        - ./.env
      depends_on:
        - db
      container_name: mindfulblogwebapp
    
volumes:
    postgres_data:
